github:
  - repo: https://github.com/jlinpw/revised_benchmark_demo.git
    branch: alltoall
    sparse_checkout:
      - setup.sh
      - run_batch.sh
      - /slurm-jobs/generic
jobs:
  setup:
    steps:
      - name: setup
        run: ./setup.sh
  run_all_to_all:
    needs:
      - setup
    steps:
      - name: Run All to All
        run: ./run_batch.sh
'on':
  execute:
    inputs:
      header:
        type: header
        text: Benchmarking Workflow
        size: 20
      resource:
        type: compute-clusters
        label: Resource
      jsource:
        type: dropdown
        label: Select benchmark to run
        tooltip: Select which built-in benchmark to run
        options:
          - label: Standard
            value: standard
          - label: Minimal
            value: minimal
        default: standard
      nnodes:
        label: Number of Nodes
        type: string
        tooltip: Number of nodes for the job
        default: '10'
      ppn:
        label: Tasks per node
        tooltip: Number of MPI nodes to run per node
        type: string
        default: '1'